In [1]:
print('hello')

hello

In [2]:
import pandas as pd 
data = {"name":["john","peter","lisa"],
         "age": [25,28,31],
         "salary":[30000,45000,25000]}
df= pd.DataFrame(data)
print(df)

    name  age  salary
0   john   25   30000
1  peter   28   45000
2   lisa   31   25000

In [9]:
import pandas as pd

data_list = [
    ["john", 25, 30000],
    ["peter", 28, 45000],
    ["lisa", 31, 25000]
]

columns = ['name', 'age', 'salary']

df2 = pd.DataFrame(data_list, columns=columns)

print(df2)

    name  age  salary
0   john   25   30000
1  peter   28   45000
2   lisa   31   25000

In [ ]:
# agar dictionary se dataframe creTE KAROGE toh colunms name pehle se hi mention honge otherwise alag se set krne pdenge

# selection and indexing of columns

In [10]:
df2

    name  age  salary
0   john   25   30000
1  peter   28   45000
2   lisa   31   25000

In [14]:
df2['name']
df2[['name','age']]

    name  age
0   john   25
1  peter   28
2   lisa   31

In [ ]:
#creating a new column

In [15]:
df2['city'] = ['chennai','hyderabad','delhi']
df2

    name  age  salary       city
0   john   25   30000    chennai
1  peter   28   45000  hyderabad
2   lisa   31   25000      delhi

In [17]:
# removing a column
df2.drop('city',axis=1,inplace=True)
df2

    name  age  salary
0   john   25   30000
1  peter   28   45000
2   lisa   31   25000

In [23]:
#selecting a row
df2.loc[0]

name       john
age          25
salary    30000
Name: 0, dtype: object

In [25]:
#selecting a subset of row and column
df2.loc[0:1][['age','salary']]

   age  salary
0   25   30000
1   28   45000

In [26]:
#conditional selection
# selsect those people whose age above than 27
df2[df2['age']>27]

    name  age  salary
1  peter   28   45000
2   lisa   31   25000