In [1]:
import pandas as pd

data = {
    "Employee_ID": [101,102,103,104,105,106,107,108,109,110,
                    111,112,113,114,115],

    "Name": ["Aman","Rohit","Neha","Karan","Priya","Rahul","Simran",
             "Arjun","Anjali","Vikas","Pooja","Mohit","Sneha","Varun","Riya"],

    "Department": ["IT","HR","Finance","IT","Marketing","IT","HR",
                   "Finance","IT","Marketing","Finance","IT","HR","Marketing","IT"],

    "Age": [24,27,29,23,31,26,28,35,25,30,32,24,27,29,26],

    "Salary": [45000,52000,68000,42000,60000,55000,48000,75000,
               50000,62000,70000,46000,51000,65000,58000],

    "Experience": [1,3,5,1,7,3,4,10,2,6,8,2,3,5,4],

    "City": ["Delhi","Meerut","Noida","Delhi","Ghaziabad","Noida",
             "Meerut","Delhi","Noida","Delhi","Meerut","Noida",
             "Delhi","Ghaziabad","Meerut"],

    "Performance_Score": [8,7,9,6,8,9,7,10,8,7,9,6,8,9,8],

    "Projects_Completed": [2,4,6,1,7,5,3,10,4,6,8,2,5,7,4]
}

df = pd.DataFrame(data)

df

,Employee_ID,Name,Department,Age,Salary,Experience,City,Performance_Score,Projects_Completed
0,101,Aman,IT,24,45000,1,Delhi,8,2
1,102,Rohit,HR,27,52000,3,Meerut,7,4
2,103,Neha,Finance,29,68000,5,Noida,9,6
3,104,Karan,IT,23,42000,1,Delhi,6,1
4,105,Priya,Marketing,31,60000,7,Ghaziabad,8,7
5,106,Rahul,IT,26,55000,3,Noida,9,5
6,107,Simran,HR,28,48000,4,Meerut,7,3
7,108,Arjun,Finance,35,75000,10,Delhi,10,10
8,109,Anjali,IT,25,50000,2,Noida,8,4
9,110,Vikas,Marketing,30,62000,6,Delhi,7,6
10,111,Pooja,Finance,32,70000,8,Meerut,9,8
11,112,Mohit,IT,24,46000,2,Noida,6,2
12,113,Sneha,HR,27,51000,3,Delhi,8,5
13,114,Varun,Marketing,29,65000,5,Ghaziabad,9,7
14,115,Riya,IT,26,58000,4,Meerut,8,4

In [3]:
df.shape

(15, 9)

In [5]:
df.describe()

,Employee_ID,Age,Salary,Experience,Performance_Score,Projects_Completed
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,108.000000,27.733333,56466.666667,4.266667,7.933333,4.933333
std,4.472136,3.326660,9977.593946,2.604026,1.162919,2.463060
min,101.000000,23.000000,42000.000000,1.000000,6.000000,1.000000
25%,104.500000,25.500000,49000.000000,2.500000,7.000000,3.500000
50%,108.000000,27.000000,55000.000000,4.000000,8.000000,5.000000
75%,111.500000,29.500000,63500.000000,5.500000,9.000000,6.500000
max,115.000000,35.000000,75000.000000,10.000000,10.000000,10.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         15 non-null     int64
 1   Name                15 non-null     object
 2   Department          15 non-null     object
 3   Age                 15 non-null     int64
 4   Salary              15 non-null     int64
 5   Experience          15 non-null     int64
 6   City                15 non-null     object
 7   Performance_Score   15 non-null     int64
 8   Projects_Completed  15 non-null     int64
dtypes: int64(6), object(3)
memory usage: 1.2+ KB

In [10]:
def square(x):
    return x**2
df["Experience"]=df["Experience"].apply(square)
df

,Employee_ID,Name,Department,Age,Salary,Experience,City,Performance_Score,Projects_Completed
0,101,Aman,IT,24,45000,1,Delhi,8,2
1,102,Rohit,HR,27,52000,9,Meerut,7,4
2,103,Neha,Finance,29,68000,25,Noida,9,6
3,104,Karan,IT,23,42000,1,Delhi,6,1
4,105,Priya,Marketing,31,60000,49,Ghaziabad,8,7
5,106,Rahul,IT,26,55000,9,Noida,9,5
6,107,Simran,HR,28,48000,16,Meerut,7,3
7,108,Arjun,Finance,35,75000,100,Delhi,10,10
8,109,Anjali,IT,25,50000,4,Noida,8,4
9,110,Vikas,Marketing,30,62000,36,Delhi,7,6
10,111,Pooja,Finance,32,70000,64,Meerut,9,8
11,112,Mohit,IT,24,46000,4,Noida,6,2
12,113,Sneha,HR,27,51000,9,Delhi,8,5
13,114,Varun,Marketing,29,65000,25,Ghaziabad,9,7
14,115,Riya,IT,26,58000,16,Meerut,8,4

In [11]:

df

,Employee_ID,Name,Department,Age,Salary,Experience,City,Performance_Score,Projects_Completed
0,101,Aman,IT,24,45000,1,Delhi,8,2
1,102,Rohit,HR,27,52000,9,Meerut,7,4
2,103,Neha,Finance,29,68000,25,Noida,9,6
3,104,Karan,IT,23,42000,1,Delhi,6,1
4,105,Priya,Marketing,31,60000,49,Ghaziabad,8,7
5,106,Rahul,IT,26,55000,9,Noida,9,5
6,107,Simran,HR,28,48000,16,Meerut,7,3
7,108,Arjun,Finance,35,75000,100,Delhi,10,10
8,109,Anjali,IT,25,50000,4,Noida,8,4
9,110,Vikas,Marketing,30,62000,36,Delhi,7,6
10,111,Pooja,Finance,32,70000,64,Meerut,9,8
11,112,Mohit,IT,24,46000,4,Noida,6,2
12,113,Sneha,HR,27,51000,9,Delhi,8,5
13,114,Varun,Marketing,29,65000,25,Ghaziabad,9,7
14,115,Riya,IT,26,58000,16,Meerut,8,4